#
# Module manifest for module 'PnP.Wsl2'
#
# Generated by: rodrigopinto
#
# Updated on:04/02/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PnP.Wsl2.psm1'

# Version number of this module.
ModuleVersion = '1.1.8'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = 'bf54fc08-8aa5-4b5b-9bdb-92f0767f5c27'

# Author of this module
Author = 'ScoutmanPt(rpinto@pdragon.co)'

# Company or vendor of this module
CompanyName = 'Perspective Dragon LDA'

# Copyright statement for this module
Copyright = '(c) ScoutmanPt(rpinto@pdragon.co), Perspective Dragon. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PnP.Wsl2 Cmdlets, module to manage WSL2 Instances'


# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport ='*'
# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData       = @{
    # app constants
    Constants = @{
        AppInsightsInstrumentationKey = '3bf937c3-8246-466d-90d7-29d53ce2e552'
        AppInsightsIngestionEndpoint = 'https://dc.services.visualstudio.com/v2/track'
    }
    PSData = @{
        Tags = 'PnP','WSL2','PowerShell','PnP.PowerShell','SPFX','Azure','SharePoint','M365','AzureDevOps','MachineLearning','Linux'
        ProjectUri = 'https://www.scoutman.pt/pnpwsl2docs'
        IconUri = 'https://www.scoutman.pt/imgs/PnPWsl2Logo.png'
    }

}  # End of PrivateData hashtable

# HelpInfo URI of this module
#  HelpInfoURI = './PnP.Wsl2-help.xml'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}


